resume
fd1-53-17/vyacheslau13 pull request #2
Opened 2017-10-30 08:33 UTC by vyacheslau13

resume, please previev

2017-10-30 17:13 UTC, vyacheslau13 commented
здравствуйте, resume можете даже не смотреть, ибо там просто ужас. посмотрите "измененное резюме"

2017-11-01 04:03 UTC, antonkulakov-it submitted a review, later dismissed

2017-11-01 04:06 UTC, antonkulakov-it requested changes

2017-11-01 04:06 UTC, antonkulakov-it commented on resume/index.html
> +     <head3>
что за новый тег?

2017-11-01 04:06 UTC, antonkulakov-it commented on resume/index.html
> +     <head4>
а это что за новый тег?

2017-11-01 04:06 UTC, antonkulakov-it commented on resume/index.html
> +     <body2>
а это что за новое тело?

2017-11-01 07:29 UTC, vyacheslau13 commented
please review

2017-11-03 04:01 UTC, antonkulakov-it approved these changes

2017-11-03 04:01 UTC, merged