triangle, please preview
fd1-53-17/vyacheslau13 pull request #5
Opened 2017-11-08 14:39 UTC by vyacheslau13

2017-11-09 15:34 UTC, antonkulakov-it requested changes

2017-11-09 15:34 UTC, antonkulakov-it commented on 08.11.2017A/triangle.html
> +        <p><div class="circle"</p>
не закрыт тег.

2017-11-09 18:15 UTC, vyacheslau13 commented
проверьте пожалуйста

2017-11-12 09:56 UTC, antonkulakov-it approved these changes

2017-11-12 09:57 UTC, merged